<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class TrackingPixelsViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_tracking_pixels_view()
    {
        $response = $this->get('shortener/tracking-pixels');

        $response->assertStatus(200)->assertViewIs('Shortener::trackingPixels.index');
    }

    public function test_tracking_pixels_create()
    {
        $response = $this->get('shortener/tracking-pixels/create');

        $response->assertViewIs('Shortener::trackingPixels.create_edit')->assertStatus(200);
    }
}
